### ISSUE TITLE
Sourcemaps in bundled version are incorrect

### ISSUE THREAD

**Issue by steveworkman** [webcomponents/template-shadowroot#39]
When using this library in a server's development mode, the sourcemaps point to files that were not distributed with the package.

For example: https://unpkg.com/@webcomponents/template-shadowroot@0.1.0/template-shadowroot.js.map points to https://unpkg.com/@webcomponents/template-shadowroot@0.1.0/src/template-shadowroot.ts which does not exist.

**Comment by augustjk** [comment]
In lieu of including the .ts source files, adding `"inlineSources": true` to the `tsconfig.json` would fix this.
